In [6]:
import torch
import numpy as np

def conv(input,kernel,stride,padding):
  if(padding>0):
    input=np.pad(input,((padding,padding),(padding,padding)),'constant',constant_values=(0))

  out_height=(input.shape[0]-kernel.shape[0])//stride+1
  out_width=(input.shape[1]-kernel.shape[1])//stride+1

  output = np.zeros((out_height,out_width))

  for x in range(out_height):
    for y in range(out_width):
      region = input[x*stride:x*stride+kernel.shape[0], y*stride:y*stride+kernel.shape[1]]
      output[x,y] = np.sum(region * kernel)
  return output

input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
kernal = np.array([[1, 0], [0, -1]])


output = conv(input_matrix,kernal,1,1)
print(output)

[[ -1.  -2.  -3.  -4.   0.]
 [ -5.  -5.  -5.  -5.   4.]
 [ -9.  -5.  -5.  -5.   8.]
 [-13.  -5.  -5.  -5.  12.]
 [  0.  13.  14.  15.  16.]]
